language: python

python:
  - "3.6"

install:
  - pip install pytest
  - pip install coverage

script:
  - cd templates && pytest

after_success:
  - cd templates && bash <(curl -s https://codecov.io/bash)