language: python

python:
  - "3.6"

install:
  - pip install pytest
  - pip install coverage
  - pip install pytest-cov

script:
  - cd templates && py.test --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)